// Generated by https://quicktype.io

namespace MyCourse.Models.Options
{
    

    public partial class ModelsOptionsCoursesOptionsCs
    {
       
        public long PerPage { get; set; }

        
        public CoursesOptions Order { get; set; }
    }

    public partial class CoursesOptions
    {
       
        public string By { get; set; }

       
        public bool Ascending { get; set; }

        
        public string[] Allow { get; set; }
    }
   
}
